"""Data models for the coach."""

from __future__ import annotations

from datetime import date, datetime
from typing import Literal

from pydantic import BaseModel, Field, field_validator

from open_coach.sports.base import ActivitySport, FitnessMarker, Intensity, SportKey, Volume

Language = Literal["en", "fr"]
"""Athlete-facing output language for text generated by the code (plan markdown, descriptions)."""

# ── Core models ──


class PaceRange(BaseModel):
    """Pace range in seconds per kilometer."""

    min_pace_sec_per_km: float  # faster (lower number)
    max_pace_sec_per_km: float  # slower (higher number)


class HRRange(BaseModel):
    """Heart rate range in BPM."""

    min_bpm: int
    max_bpm: int


class ZoneInfo(BaseModel):
    """Combined pace and HR info for a training zone."""

    pace: PaceRange | None = None
    hr: HRRange | None = None


class TrainingZones(BaseModel):
    """Training zones derived from VDOT and/or HR."""

    easy: ZoneInfo
    marathon: ZoneInfo
    threshold: ZoneInfo
    interval: ZoneInfo
    repetition: ZoneInfo


class ActivitySummary(BaseModel):
    """Summary of a single activity."""

    activity_id: int
    date: date
    sport: ActivitySport
    distance_m: float
    duration_s: float
    avg_hr: int | None = None
    max_hr: int | None = None
    elevation_gain_m: float | None = None
    name: str = ""


class ActivityCache(BaseModel):
    """Versioned envelope for the persisted activity summary cache."""

    schema_version: int = 2
    activities: list[ActivitySummary] = Field(default_factory=list)


class TrainingLoadPoint(BaseModel):
    """A single data point in the training load time series."""

    date: date
    tss: float
    ctl: float  # Chronic Training Load (fitness)
    atl: float  # Acute Training Load (fatigue)
    tsb: float  # Training Stress Balance (form)


# ── Persistence models ──


class PersonalRecord(BaseModel):
    """A personal record at a specific distance."""

    distance_label: str  # "5K", "10K", "half_marathon", "marathon"
    distance_m: float
    time_s: float
    activity_id: int
    date: date
    # platform_pr = reported by the watch platform, detected = inferred from activities
    source: Literal["platform_pr", "detected"] = "detected"

    @field_validator("source", mode="before")
    @classmethod
    def _legacy_source(cls, value: object) -> object:
        # profile.json files written before the watch-provider layer say "garmin_pr".
        return "platform_pr" if value == "garmin_pr" else value


class TrainingPattern(BaseModel):
    """Summary of recent training habits in one sport."""

    weekly_distance_m: float
    weekly_duration_s: float = 0.0
    weekly_frequency: float  # sessions per week
    long_session_avg_distance_m: float
    long_session_avg_duration_s: float = 0.0
    easy_intensity: Intensity | None = None
    analysis_window_days: int = 180
    computed_at: datetime


class SportProfile(BaseModel):
    """What the coach knows about the athlete in one sport."""

    fitness: FitnessMarker | None = None
    personal_records: list[PersonalRecord] = Field(default_factory=list)
    training_pattern: TrainingPattern | None = None


class AthleteProfile(BaseModel):
    """Persistent athlete profile stored in ~/.open-coach/profile.json."""

    schema_version: int = 2

    # Core physiology (shared by every sport)
    max_hr: int | None = Field(default=None, gt=0)
    resting_hr: int | None = Field(default=None, gt=0)
    threshold_hr: int | None = Field(default=None, gt=0)
    weight_kg: float | None = Field(default=None, gt=0)

    # Per-sport fitness, records and training pattern
    sports: dict[SportKey, SportProfile] = Field(default_factory=dict)

    # CTL/ATL snapshot (recomputed periodically)
    ctl: float | None = None
    atl: float | None = None
    tsb: float | None = None

    # Metadata
    created_at: datetime | None = None
    updated_at: datetime | None = None
    onboarding_complete: bool = False
    language: Language = "en"

    def sport_profile(self, sport: SportKey, create: bool = False) -> SportProfile:
        """The athlete's block for *sport* (an empty one if absent; stored when *create*)."""
        existing = self.sports.get(sport)
        if existing is not None:
            return existing
        block = SportProfile()
        if create:
            self.sports[sport] = block
        return block


class TrainingGoal(BaseModel):
    """A target race or training goal."""

    sport: SportKey
    race_name: str | None = None
    distance_m: float
    race_date: date | None = None
    target_time_s: float | None = None
    priority: Literal["A", "B", "C"] = "A"
    created_at: datetime | None = None


class GoalsConfig(BaseModel):
    """Container for training goals."""

    schema_version: int = 2
    goals: list[TrainingGoal] = Field(default_factory=list)
    updated_at: datetime | None = None


class InjuryRecord(BaseModel):
    """Record of an injury affecting training."""

    description: str
    body_part: str
    severity: Literal["minor", "moderate", "severe"] = "minor"
    date_reported: date
    resolved: bool = False
    resolved_date: date | None = None


class TrainingConstraints(BaseModel):
    """Athlete's training constraints and availability."""

    schema_version: int = 1
    available_days: list[str] = Field(default_factory=list)  # ["monday", "wednesday", ...]
    max_sessions_per_week: int | None = None
    max_weekday_minutes: int | None = None
    max_weekend_minutes: int | None = None
    injuries: list[InjuryRecord] = Field(default_factory=list)
    notes: str | None = None
    updated_at: datetime | None = None


class WorkoutFeedback(BaseModel):
    """Subjective + objective feedback for a completed workout."""

    activity_id: int | None = None
    date: date
    sport: SportKey | None = None
    workout_type: str  # a session type of the sport (Sport.workout_types)

    # Subjective
    perceived_effort: Literal["too_easy", "easy", "moderate", "hard", "too_hard"] | None = None
    feeling: Literal["great", "good", "okay", "tired", "terrible"] | None = None
    notes: str | None = None

    # Objective (auto-filled from the watch platform if activity_id provided)
    planned_distance_m: float | None = None
    actual_distance_m: float | None = None
    actual_duration_s: float | None = None
    planned_intensity: Intensity | None = None
    actual_intensity: Intensity | None = None
    avg_hr: int | None = None

    recorded_at: datetime | None = None


class FeedbackLog(BaseModel):
    """Quarterly feedback log."""

    schema_version: int = 2
    period: str  # "2026-Q2"
    entries: list[WorkoutFeedback] = Field(default_factory=list)


class PlannedWorkout(BaseModel):
    """A single workout in a training plan."""

    date: date
    sport: SportKey | None = None  # None = the plan's sport (goal.sport)
    workout_type: str  # a session type of the sport, or rest / strength
    description: str
    target_distance_m: float | None = None
    target_duration_s: float | None = None
    target_intensity: Intensity | None = None

    # Actuals (filled post-workout)
    completed: bool = False
    actual_activity_id: int | None = None
    actual_distance_m: float | None = None
    actual_duration_s: float | None = None
    actual_intensity: Intensity | None = None
    skipped_reason: str | None = None


class ExtraActivity(BaseModel):
    """An unplanned activity logged against a training week (counts toward actual volume)."""

    date: date
    sport: SportKey
    distance_m: float
    duration_s: float = 0.0
    activity_id: int | None = None
    name: str | None = None


class TrainingWeek(BaseModel):
    """A week within a training plan."""

    week_number: int
    start_date: date
    planned_volume: dict[SportKey, Volume] = Field(default_factory=dict)
    actual_volume: dict[SportKey, Volume] = Field(default_factory=dict)
    completion_rate: float = 0.0  # 0.0 to 1.0
    workouts: list[PlannedWorkout] = Field(default_factory=list)
    extra_activities: list[ExtraActivity] = Field(default_factory=list)
    notes: str | None = None


class TrainingPlan(BaseModel):
    """A complete training plan."""

    schema_version: int = 2
    name: str
    goal: TrainingGoal
    start_date: date
    end_date: date
    weeks: list[TrainingWeek] = Field(default_factory=list)
    status: Literal["active", "completed", "abandoned"] = "active"

    # Outcome tracking
    outcome_notes: str | None = None
    race_result_s: float | None = None

    created_at: datetime | None = None
    updated_at: datetime | None = None

    def sport_of(self, workout: PlannedWorkout) -> SportKey:
        """The sport of *workout* (its own, else the plan's)."""
        return workout.sport or self.goal.sport


class WorkoutUpload(BaseModel):
    """Record of a workout uploaded to the watch platform."""

    workout_id: int
    name: str
    uploaded_at: datetime
    provider: str = "garmin"  # WatchProvider.name; older registries predate the field
    schedule_ids: list[int] = Field(default_factory=list)
    schedule_dates: list[date] = Field(default_factory=list)
    deleted: bool = False


class WorkoutRegistry(BaseModel):
    """Registry of all coach-created workouts (for idempotent cleanup)."""

    schema_version: int = 1
    workouts: list[WorkoutUpload] = Field(default_factory=list)

    def find(self, workout_id: int) -> WorkoutUpload | None:
        return next((w for w in self.workouts if w.workout_id == workout_id), None)

    def active_workouts(self) -> list[WorkoutUpload]:
        return [w for w in self.workouts if not w.deleted]


# ── Race prediction models (Phase 4) ──


class RacePrediction(BaseModel):
    """Predicted race time with confidence interval."""

    distance_label: str  # "5K", "10K", "Half Marathon", "Marathon"
    distance_m: float
    predicted_time_s: float
    confidence_low_s: float  # optimistic bound (faster)
    confidence_high_s: float  # conservative bound (slower)
    predicted_pace_sec_per_km: float


class PacingSplit(BaseModel):
    """A single split in a pacing strategy."""

    split_km: float  # size of the split (1.0, 5.0)
    split_label: str  # "km 1", "5-10K"
    target_pace_sec_per_km: float
    cumulative_time_s: float
    effort_note: str  # coaching cue


class PacingStrategy(BaseModel):
    """Complete pacing plan for a race."""

    distance_label: str
    distance_m: float
    strategy_name: str  # "even_effort", "negative_split", "conservative_start"
    target_time_s: float
    splits: list[PacingSplit]
    key_guidance: list[str]  # 3-5 coaching bullet points


class ReadinessComponent(BaseModel):
    """A single scored component of race readiness."""

    name: str
    score: float  # 0.0 to 1.0
    status: Literal["ready", "caution", "not_ready"]
    detail: str


class RaceReadiness(BaseModel):
    """Comprehensive race readiness assessment."""

    overall_score: float  # 0.0 to 1.0
    overall_status: Literal["ready", "caution", "not_ready"]
    summary: str
    components: list[ReadinessComponent]
    recommendations: list[str]
    days_to_race: int | None = None


# ── Recovery monitoring models (Phase 5) ──


class RecoverySignal(BaseModel):
    """A single scored component of recovery assessment."""

    name: str  # "HRV", "Sleep", "TSB", "Stress", "Subjective"
    score: float  # 0.0 to 1.0
    status: Literal["green", "yellow", "red"]
    value: str  # human-readable: "HRV 52ms (baseline 48ms)"
    detail: str
    # False when the watch/feedback gave no data: the neutral score still counts
    # in the overall score, but the signal never drives the summary or advice.
    available: bool = True


class RecoveryAssessment(BaseModel):
    """Composite recovery evaluation from multiple signals."""

    date: date
    overall_score: float  # 0-100
    status: Literal["green", "yellow", "red"]
    signals: list[RecoverySignal]
    summary: str
    recommendations: list[str]


class AdaptiveRecommendation(BaseModel):
    """Concrete workout adjustment based on recovery status."""

    action: Literal["proceed", "reduce_intensity", "reduce_volume", "swap_to_easy", "rest_day"]
    reasoning: str
    original_workout: str | None = None
    adjusted_workout: str | None = None
    intensity_reduction_pct: float | None = None
